### ISSUE TITLE
KeyError: 'follow'

### ISSUE THREAD

**Issue by drzraf** [yaegashi/ansible-role-blockinfile#4]
With these two lines:
```
if module.boolean(params['follow']):
      dest = os.path.realpath(dest)
```
Ansible (1.7.2) fails with:
```
Traceback (most recent call last):
  File "<stdin>", line 1591, in <module>
  File "<stdin>", line 153, in main
KeyError: 'follow'
```
Setting a follow parameter throws:
```msg: unsupported parameter for module: follow```

**Comment by yaegashi** [comment]
Fixed in v0.4.
